from pathlib import Path
p=Path('src/ui/HomeScreen.tsx');s=p.read_text(encoding='utf-8')
s=s.replace('>{false ? goalName : '+chr(96)+'Цель: '+chr(36)+'{goalName}'+chr(96)+'}',">{'Цель: ' + goalName}")
s=s.replace("largeHud: { padding: 10, gap: 8, backgroundColor: '#F8F1E8E8' }","largeHud: { padding: 10, gap: 8 }")
s=s.replace('showCaption={false} fullscreen','showCaption={false} roomOpacity={large ? .14 : 1} fullscreen')
a=s.index('<View style={styles.sceneCopy}><Pressable');b=s.index('<View style={styles.inlineState}>',a)
s=s[:a]+'<View style={styles.sceneCopy}>'+s[b:]
s=s.replace('x: layout.x + 4, y: layout.y + 140, width: Math.max(80, layout.width - 92), height: Math.max(60, layout.height - 208)', 'x: layout.x + (size.height < 700 ? 70 : 4), y: layout.y + 112, width: Math.max(80, layout.width - (size.height < 700 ? 148 : 92)), height: Math.max(60, layout.height - (size.height < 700 ? 116 : 180))')
s=s.replace('style={styles.ordinaryPetTarget}',"style={[styles.ordinaryPetTarget, size.height < 700 && { left: 70, right: 78, bottom: 0 }]}")
s=s.replace("inlineState: { paddingHorizontal: 12, paddingBottom: 6 }","inlineState: { paddingHorizontal: 12, paddingTop: 8, paddingBottom: 4 }")
s=s.replace("left: 4, top: 140, bottom: 68", "left: 4, top: 112, bottom: 68")
s=s.replace("careAnchor: { left: '41%', bottom: 0 }","careAnchor: { right: 0, bottom: 72 }")
s=s.replace("<Text style={[text, styles.bold]}>{'Цель: ' + goalName}</Text>","<View style={styles.goalHeading}>{!large && <Image accessible={false} source={goalSource(goal?.id ?? null) ?? OBJECT_SOURCES['OBJ-GOAL-DISPLAY']} resizeMode=\"contain\" style={styles.goalIcon} />}<Text style={[text, styles.bold, styles.goalTitle]}>{'Цель: ' + goalName}</Text></View>")
s=s.replace("largeGoal: { paddingTop: 6, marginTop: 6 },","largeGoal: { paddingTop: 6, marginTop: 6 }, goalHeading: { flexDirection: 'row', alignItems: 'center', gap: 6 }, goalIcon: { width: 24, height: 24 }, goalTitle: { flex: 1 },")
p.write_text(s,encoding='utf-8')
p=Path('src/ui/FinniHomeScene.tsx');s=p.read_text(encoding='utf-8')
s=s.replace('  fullscreen?: boolean;', '  fullscreen?: boolean;\n  roomOpacity?: number;')
s=s.replace("props.fullscreen && { borderRadius: 0 }","props.fullscreen && { borderRadius: 0, backgroundColor: '#F8F1E8' }")
s=s.replace('style={styles.layer}', 'style={[styles.layer, { opacity: props.roomOpacity ?? 1 }]}')
p.write_text(s,encoding='utf-8')